name: Pis Suni Kropli
author: Aleks
description: Pis Suni Kropli is an automatically updating, easily customizable theme for Discord.

baseurl: ""

exclude:
    - README.md
    - Gemfile

plugins:
    - jekyll-redirect-from

sass:
    style: compressed